name: Build Melviz and Upload Artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven and zip resulting package
      id: build
      run: mvn package && zip -r melviz-webapp-parent/melviz-webapp/target/melviz-webapp.zip ./melviz-webapp-parent/melviz-webapp/target/melviz-webapp

    - name: Upload MelvizWebApp
      uses: actions/upload-artifact@v4
      with:
        name: MelvizWebApp
        path: ./melviz-webapp-parent/melviz-webapp/target/melviz-webapp.zip
        if-no-files-found: warn
        overwrite: true
